server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gatling-lab
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
